name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # 2 PM Pakistan = 09:00 UTC
    - cron: "0 9 * * *"
    # 4 PM Pakistan = 11:00 UTC
    - cron: "0 11 * * *"

jobs:

  full:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run All Tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-full
          path: playwright-report/
          retention-days: 30

      - name: Trigger Repo1
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO1_TOKEN }}" \
          https://api.github.com/repos/Arfaa49/automation-repo-1/actions/workflows/tests.yml/dispatches \
          -d '{"ref":"main"}'

  smoke:
    if: github.event.schedule == '0 9 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: npx playwright test --grep smoke

      - name: Trigger Repo1
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO1_TOKEN }}" \
          https://api.github.com/repos/Arfaa49/automation-repo-1/actions/workflows/tests.yml/dispatches \
          -d '{"ref":"main"}'

  regression:
    if: github.event.schedule == '0 11 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run Regression Tests
        run: npx playwright test --grep regression

      - name: Trigger Repo1
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO1_TOKEN }}" \
          https://api.github.com/repos/Arfaa49/automation-repo-1/actions/workflows/tests.yml/dispatches \
          -d '{"ref":"main"}'
